### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by llmir** [DeepTrial/Optic-Disc-Unet#4]
[INFO] Saving Training Data
Traceback (most recent call last):
  File "main_train.py", line 54, in <module>
    main_train()
  File "main_train.py", line 35, in main_train
    dataloader.prepare_dataset()
  File "/home/mir/Optic-Disc-Unet/experiments/data_loaders/standard_loader.py", line 69, in prepare_dataset
    imgs_val, groundTruth = self._access_dataset(self.val_img_path, self.val_groundtruth_path, self.val_type)
  File "/home/mir/Optic-Disc-Unet/experiments/data_loaders/standard_loader.py", line 48, in _access_dataset
    imgs[index,:,:,0]=np.asarray(orgImg[:,:,1]*0.75+orgImg[:,:,0]*0.25)
ValueError: could not broadcast input array from shape (400,599) into shape (400,600)

**Comment by llmir** [comment]
actually it's because the size of image_101 is 599*400, you can resize it or remove it.
